apiVersion: apps/v1
kind: Deployment
metadata:
  name: resign-api-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: resign-api
  template:
    metadata:
      labels:
        app: resign-api
    spec:
      containers:
      - name: backend
        image: resign-api-backend:v10 
        imagePullPolicy: Never 
        ports:
        - containerPort: 8686
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres.ehfpuftaavkbjufvmxtm:wesfuh-Xodba8-sovroj@aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres"
        resources:
          limits:
            cpu: "200m"    
          requests:
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: resign-api-service
spec:
  type: LoadBalancer
  selector:
    app: resign-api
  ports:
    - protocol: TCP
      port: 8686       
      targetPort: 8686 