apiVersion: apps/v1
kind: Deployment
metadata:
  name: resign-api-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: resign-api
  template:
    metadata:
      labels:
        app: resign-api
    spec:
      containers:
      - name: backend
        image: resign-api-backend:v6 # Pastiin tag-nya sesuai versi terakhir lo
        imagePullPolicy: Never 
        ports:
        - containerPort: 8686
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres.ehfpuftaavkbjufvmxtm:wesfuh-Xodba8-sovroj@aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres"
        # RESOURCES HARUS DI SINI (Sejajar sama env, di bawah name/image)
        resources:
          limits:
            cpu: "200m"    
          requests:
            cpu: "100m"