apiVersion: apps/v1
kind: Deployment
metadata:
  name: resign-api-deployment
spec:
  replicas: 1 # Kita mulai dari 1 pod dulu
  selector:
    matchLabels:
      app: resign-api
  template:
    metadata:
      labels:
        app: resign-api
    spec:
      containers:
      - name: backend
        image: resign-api-backend:v3 # Pake image yang barusan lo build
        imagePullPolicy: Never # Paksa K8s pake image lokal dari OrbStack
        ports:
        - containerPort: 8686
        env:
        # Masukin ENV Supabase lo di sini biar apps bisa konek
        - name: DATABASE_URL
          value: "postgresql://postgres.ehfpuftaavkbjufvmxtm:wesfuh-Xodba8-sovroj@aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres"