name: CI/CD Pipeline POROS

on:
  push:
    branches: [ master ] # Pipeline jalan tiap lo push ke branch main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Stage Build & Push Backend
      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/resign-api-backend:latest

      # Stage Build & Push Frontend
      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/resign-api-frontend:latest

  deploy-locally:
    needs: build-and-push
    runs-on: self-hosted # Ini trik biar nembak ke laptop lo langsung
    steps:
      - name: Pull and Restart K8s
        run: |
          kubectl rollout restart deployment resign-api-deployment
          kubectl rollout restart deployment resign-api-frontend

# Ini trik biar nembak ke laptop 
# Ini trik biar nembak ke laptop 